#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Project by
# Ludovic Fernandez
# http://github.com/Wrexes

"""
DotManager: A flexible dotfile manager

Usage:
  dot list [supported | installed | saved]
  dot save [all | <app>] [<name>] [<user>] [-f | --force] [--nolink] [--noload]
  dot load [all | <app>] [<name>] [<user>] [-f | --force] [--nolink]

Options:
  -h --help    Show this screen.
  --version    Show version.
  -f, --force  Overwrite existing configurations.
  --noload     Don't load the saved configuration.
  --nolink     Prefer copying files instead of using symlinks.

Commands:
  list:
    supported  Apps that DotManager has a dotinfo for.
    installed  Supported apps that is intalled on your machine.
    saved      Configurations that you have saved.

  save & load:
    [all| <app>]  Choose which app to save the configuration of.
                   - If `all`, save every installed apps' configurations.
                   - If the name of a supported app, save its configurations.
                   - If left empty, go through the list of possible
                     choices interactively.

    [<name>]      Name of the configuration.
                  Default: "default"

    [<user>]      "Owner" of the configuration.
                  Default: Your username
"""

import docopt

import commands
import config
import tools
import dotinfo


argv = docopt.docopt(__doc__, version='0.0.0')


def main(argv):
    if argv["list"]:
        if argv["supported"]:
            commands.list.supported()
            return
        if argv["installed"]:
            commands.list.installed()
            return
        # if argv["saved"]:
            # commands.list.saved()
            # return

    if argv["save"]:
        dots = dotinfo.installed()
        params = {"overwrite": argv["--force"]}
        if argv["<user>"]:
            params["userName"] = argv["<user>"]
        if argv["<name>"]:
            params["confName"]

        # Single app selected
        if argv["<app>"]:
            if argv["<app>"] not in dots.keys():
                tools.eprint("App not found: " + argv["<app>"] + "\n" +
                             "Please use the `list` command to make sure it is supported and installed.")
                exit(1)
            params["dot"] = dots[argv["<app>"]]
            commands.save.save(**params)
            return

        # All apps
        elif argv["all"]:
            for item in dots.values():
                print("Found supported app: " + item.name)
                params["dot"] = item
                commands.save.save(**params)

        # Interactive
        # TODO: Make menus (something like `yay`'s)
        for item in dots.values():
            print("Found supported app: " + item.name)
            while answer := 'x' + str(input("Would you like to save it ? (Y/n): ")).lower():
                if answer == 'xn':
                    break
                elif answer in ['xy', 'x']:
                    params["dot"] = item
                    commands.save.save(**params)
                    break
                else:
                    continue


if __name__ == "__main__":
    main(argv)
