#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# MIT License

# Copyright (c) 2020 Ludovic Fernandez

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
DotManager: A flexible dotfile manager

Usage:
  dot list [supported | installed | saved]
  dot save [all | <app>] [<name>] [<user>] [-f | --force] [--nolink]
  dot load [all | <app>] [<name>] [<user>] [-f | --force] [--nolink]

Options:
  -h --help    Show this screen.
  --version    Show version.
  -f, --force  Overwrite existing configurations.
  --nolink     Prefer copying files instead of using symlinks.

Commands:
  list:
    supported  Apps that DotManager has a dotinfo for.
    installed  Supported apps that is intalled on your machine.
    saved      Configurations that you have saved.

  save & load:
    [all| <app>]  Choose which app to save the configuration of.
                   - If `all`, save every installed apps' configurations.
                   - If the name of a supported app, save its configurations.
                   - If left empty, go through the list of possible
                     choices interactively.

    [<name>]      Name of the configuration.
                  Default: "default"

    [<user>]      "Owner" of the configuration.
                  Default: Your username
"""

import docopt

import DotManager.tools as tools
import DotManager.config as config
import DotManager.dotinfo as dotinfo
import DotManager.commands as commands
from DotManager.defaults import version


argv = docopt.docopt(__doc__, version=version)


def main(argv):
    if argv["list"]:
        if argv["supported"]:
            commands.list.supported()
            return
        if argv["installed"]:
            commands.list.installed()
            return
        if argv["saved"]:
            print("I'm sorry, this feature is not yet available.")
            return
            # commands.list.saved()
            # return

    if argv["save"]:
        dots = dotinfo.installed()
        params = {"overwrite": argv["--force"]}
        if argv["<user>"]:
            params["userName"] = argv["<user>"]
        if argv["<name>"]:
            params["confName"]

        # Single app
        if argv["<app>"]:
            if argv["<app>"] not in dots.keys():
                tools.eprint("App not found: " + argv["<app>"] + "\n" +
                             "Please use the `list` command to make sure it is supported and installed.")
                exit(1)
            params["dot"] = dots[argv["<app>"]]
            commands.save.save(**params)
            return

        # All apps
        # TODO: Make menus (something like `yay`'s)
        elif argv["all"]:
            for item in dots.values():
                print("Found supported app: " + item.name)
                params["dot"] = item
                commands.save.save(**params)

        # Interactive
        # TODO: Make menus (something like `yay`'s)
        for item in dots.values():
            print("Found supported app: " + item.name)
            while answer := 'x' + str(input("Would you like to save it ? (Y/n): ")).lower():
                if answer == 'xn':
                    break
                elif answer in ['xy', 'x']:
                    params["dot"] = item
                    commands.save.save(**params)
                    break
                else:
                    continue
        return

    if argv["load"]:
        print("I'm sorry, this feature is not yet available.")
        return


if __name__ == "__main__":
    main(argv)
