#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Project by
# Ludovic Fernandez
# http://github.com/Wrexes

import shutil
import os
from fnmatch import fnmatch
from glob import glob as wildcard

import tools
import dot

